library kinohome.globals;

String id = "";
String? ids = "";
String apiUrl = "";
String podbName = "";
String imdb = "";
String tvname = "";
String year = "";
int season = 0;
String watchLink = "";
String monetColor = "";
int episode = 0;
String filmLink = "";
String lanId = "";
bool isTVC = false;
String baseUrl = "http://65.21.93.57:51058";
String title = "";
final String newUrl = "http://65.21.93.57:51058/getNew?api_token=Q2srILqHm5IJUKcfiTh5TURHgy5WJkA9";
final String popularUrl = "http://65.21.93.57:51058/getNow?api_token=Q2srILqHm5IJUKcfiTh5TURHgy5WJkA9";
final String topUrl = "http://65.21.93.57:51058/getTop?api_token=Q2srILqHm5IJUKcfiTh5TURHgy5WJkA9";
List<dynamic> l = [];
bool serial = false;
bool isPremium = false;
String video = "";
String banner = "";
bool adblockNeedKey = false;
String actorID = "";
String selectedGenre = "";
String selectedCountry = "";
String selectedGenreID = "0";
String selectedCountryID = "0";
String minYear = "1000";
String maxYear = "3000";
String minRating = "0";
String maxRating = "10";
String lastEpisode = "";
